[package]
name = "deadlock-repro"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[dependencies]
# tokio = "0.1.7"
tokio = { git = "https://github.com/tokio-rs/tokio.git" }
futures = "0.1.23"
log = "0.4"
env_logger = "0.5"
